# Generated by Django 2.0 on 2017-12-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image_path',
        ),
        migrations.AddField(
            model_name='video',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
